name: Build

on:
  workflow_dispatch:
    inputs:
      rubin_env:
        description: "rubin-env version"
        required: true
        default: "8.0.0"
        type: string
      base_tag:
        description: "Base container tag suffix"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rhel: [9]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ matrix.rhel }}-${{ inputs.base_tag }}-${{ inputs.rubin_env }}
          file: Dockerfile
          build-args: |
            LSST_SPLENV_REF=${{ inputs.rubin_env }}
            BASE_IMAGE=ghcr.io/lsst-dm/docker-scipipe:${{ matrix.rhel }}-${{ inputs.base_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
